### ISSUE TITLE
"Unknown piece-place-enum" when adding fragment on top of fragment with BoomMenu

### ISSUE THREAD

**Issue by amanzan** [Nightonke/BoomMenu#121]
I have a fragment with BoomMenu in the Toolbar and it works just fine. Then I try to add a new Fragment on top, with the BoomMenu invisible (replaced by a back arrow) and I am getting this exception.

Log doesn't point to any line in my code, this is all I get:
`java.lang.RuntimeException: Unknown piece-place-enum!
                                                                                   at com.nightonke.boommenu.ExceptionManager.judge(ExceptionManager.java:61)
                                                                                   at com.nightonke.boommenu.ExceptionManager.judge(ExceptionManager.java:23)
                                                                                   at com.nightonke.boommenu.BoomMenuButton.doLayoutJobs(BoomMenuButton.java:348)
                                                                                   at com.nightonke.boommenu.BoomMenuButton.access$600(BoomMenuButton.java:55)
                                                                                   at com.nightonke.boommenu.BoomMenuButton$8.run(BoomMenuButton.java:1016)
                                                                                   at android.os.Handler.handleCallback(Handler.java:751)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                   at android.os.Looper.loop(Looper.java:154)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:6121)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)`

Any ideas what could be the problem?

**Comment by Nightonke** [comment]
This means the piece-place-enum of BMB is not set yet.

**Comment by amanzan** [comment]
Ok, so that needs to be set even if BoomMenu is not visible. Makes sense, I changed my implementation and now I only add the BoomMenu when needed. Thanks! Awesome library :)

**Comment by Nightonke** [comment]
Thank you. Enjoy it.
