### ISSUE TITLE
Limited Pieces&Button and set onclick listener

### ISSUE THREAD

**Issue by venkateshj99** [Nightonke/BoomMenu#122]
Trying to implement Ham Button with 6 Pieces&Button. ClickOnListener for any button to new activity with button title. How do i do this? Help me bro.

**Comment by Nightonke** [comment]
[Click event wiki](https://github.com/Nightonke/BoomMenu/wiki/Click-Event-and-Listener) will tell you.

**Comment by venkateshj99** [comment]
Thank you very much Bro. I got It !:)

**Comment by venkateshj99** [comment]
IndexOutOfBound issue
I have set the limited Pieces&Button in BuilderManager and used ListenerExample like this in MainActivity as, 
        assert bmb != null;
        bmb.setButtonEnum(ButtonEnum.Ham);
        bmb.setPiecePlaceEnum(PiecePlaceEnum.HAM_6);
        bmb.setButtonPlaceEnum(ButtonPlaceEnum.HAM_6);

        for (int i = 0; i < bmb.getPiecePlaceEnum().pieceNumber(); i++) addBuilder();

        bmb.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
            }
        });
        // Use OnBoomListenerAdapter to listen part of methods
        bmb.setOnBoomListener(new OnBoomListenerAdapter() {
            @Override
            public void onBoomWillShow() {
                super.onBoomWillShow();
            }
        });
    }
    private void addBuilder() {
        bmb.addBuilder(new HamButton.Builder()
                .normalImageRes(BuilderManager.getImageResource())
                .normalText(BuilderManager.getTitleResource())
                .subNormalText(BuilderManager.getSubTitleResource())
                .listener(new OnBMClickListener() {
                    @Override
                    public void onBoomButtonClick(int index) {
                        Toast.makeText(getApplicationContext(), "Selected" + index,
                                Toast.LENGTH_SHORT).show();
                        //textViewForButton.setText("No." + index + " boom-button is clicked!");
                    }
                }));
    }
This throwing Error at run time and appearing in Xml layout too..
IndexOutOfBound Index: 0, Size: 0
 at java.util.ArrayList.rangeCheck(ArrayList.java:604)   at java.util.ArrayList.get(ArrayList.java:382)   at crystal.sked.boommenu.BoomMenuButton.createPieces(BoomMenuButton.java:404)   at crystal.sked.boommenu.BoomMenuButton.doLayoutJobs(BoomMenuButton.java:386)   at crystal.sked.boommenu.BoomMenuButton.onLayout_Original(BoomMenuButton.java:372)   at crystal.sked.boommenu.BoomMenuButton.onLayout(BoomMenuButton.java:-1) 

Is there anything i need to change in BoomMenuButton?

**Comment by Nightonke** [comment]
This is quite a strange crash... Could you please provide the xml code and the total log of the crash? Thank you.

**Comment by venkateshj99** [comment]
Sure, xml layout 
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0   
at java.util.ArrayList.rangeCheck(ArrayList.java:604)   
at java.util.ArrayList.get(ArrayList.java:382)   
at crystal.sked.boommenu.BoomMenuButton.createPieces(BoomMenuButton.java:404)   
at crystal.sked.boommenu.BoomMenuButton.doLayoutJobs(BoomMenuButton.java:386)   
at crystal.sked.boommenu.BoomMenuButton.onLayout_Original(BoomMenuButton.java:372)   
at crystal.sked.boommenu.BoomMenuButton.onLayout(BoomMenuButton.java:-1)   
at android.view.View.layout(View.java:16630)   at android.view.ViewGroup.layout(ViewGroup.java:5437)   
at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)   at android.view.View.layout(View.java:16630)   
at android.view.ViewGroup.layout(ViewGroup.java:5437)  
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)   
at android.widget.FrameLayout.onLayout(FrameLayout.java:273)   at android.view.View.layout(View.java:16630)  
at android.view.ViewGroup.layout(ViewGroup.java:5437)   
at android.support.v7.widget.ActionBarOverlayLayout.onLayout_Original(ActionBarOverlayLayout.java:437)   
at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:-1)   
at android.view.View.layout(View.java:16630)   at android.view.ViewGroup.layout(ViewGroup.java:5437)   
at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)   at android.view.View.layout(View.java:16630)   
at android.view.ViewGroup.layout(ViewGroup.java:5437) Copy stack to clipboard (2 similar errors not shown)

**Comment by Nightonke** [comment]
Are you using the [newest version(2.1.0)](https://github.com/Nightonke/BoomMenu/wiki/Version-History#v210) of BMB? I didn't get any useful information from the crash-log. I suggest you to try the newest version. If it still crash, you can send the codes to me(2584541288@qq.com). I will have a check. Thanks.

**Comment by venkateshj99** [comment]
Yes same version only, 
Gradle Version: 2.10
Android Plugin Version: 2.1.0
JDK is 8

Will try to send the code!
one more thing i have come across the site while searching for the issue, 
 https://examples.javacodegeeks.com/java-basics/exceptions/java-lang-arrayindexoutofboundsexception-how-to-handle-array-index-out-of-bounds-exception/

is there any code needs change depends on jdk7 and jdk8 for array issue

**Comment by venkateshj99** [comment]
just got time to write.., The cause of issue was i commented some lines in PiecePlaceEnum..after un-comment it not throw the error..just clean and rebuild helps to run..(it was my mistake).

**Comment by venkateshj99** [comment]
Hi Bro,
I am getting ClassCastException  issue on device for onBoomButtonClick, the same error is not throwing while running in emulator.
emulator : API 19(4.4.2), 
Device : Asus_Z00LD, API 5.0.2(Lollypop).

LogCat:
java.lang.ClassCastException: android.graphics.drawable.StateListDrawable cannot be cast to android.graphics.drawable.GradientDrawable
at sked.boommenu.Util.getRectangleDrawable(Util.java:160)
at sked.boommenu.BoomButtons.BoomButton.initHamButtonDrawable(BoomButton.java:438)
at sked.boommenu.BoomButtons.BoomButton.initHamButton(BoomButton.java:478)
at sked.boommenu.BoomButtons.HamButton.init(HamButton.java:35)
at sked.boommenu.BoomButtons.HamButton.<init>(HamButton.java:28)
at sked.boommenu.BoomButtons.HamButton.<init>(HamButton.java:22)
at crystal.sked.boommenu.BoomButtons.HamButton$Builder.build(HamButton.java:555)
at sked.boommenu.BoomButtons.HamButton$Builder.build(HamButton.java:119)
at sked.boommenu.BoomMenuButton.createButtons(BoomMenuButton.java:843)
at sked.boommenu.BoomMenuButton.innerBoom(BoomMenuButton.java:553)
at sked.boommenu.BoomMenuButton.boom(BoomMenuButton.java:538)
at sked.boommenu.BoomMenuButton$1.onClick(BoomMenuButton.java:310)
at android.view.View.performClick(View.java:4776)
at android.view.View$PerformClick.run(View.java:19793)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5289)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by Nightonke** [comment]
That's too weird. This is the method `Util.getRectangleDrawable`:
```
public static GradientDrawable getRectangleDrawable(View view, int cornerRadius, int color) {
    GradientDrawable gradientDrawable = (GradientDrawable) getDrawable(
            view,
            R.drawable.shape_rectangle_normal);
    gradientDrawable.setCornerRadius(cornerRadius);
    gradientDrawable.setColor(color);
    return gradientDrawable;
}
```
And the `shape_rectangle_normal` is absolutely a `shape-drawable-xml` [file](https://github.com/Nightonke/BoomMenu/blob/master/boommenu/src/main/res/drawable/shape_rectangle_normal.xml). It should be a `GradientDrawable` when creating from the resource file. I wonder whether this happens because the cache mechanism when loading drawable in Android. Maybe you can try to uninstall your app and try again.

**Comment by venkateshj99** [comment]
Yes tried uninstall/reinstall but still throwing the classcastexcception error..

**Comment by congdanh1608** [comment]
Hi @venkateshj99 !
I got same your error. I can fix that by my way :D (ver 2.1.0)
I try removing attribute of BoomMenu in xml:
`app:bmb_normalColor="@android:color/holo_orange_light"
    app:bmb_highlightedColor="@android:color/holo_orange_dark"
    app:bmb_buttonEnum="simpleCircle"
    app:bmb_piecePlaceEnum="piecePlace_dot_9_1"
    app:bmb_buttonPlaceEnum="buttonPlace_sc_9_1"
    app:bmb_boomInWholeScreen="false"
    app:bmb_inFragment="true" `

And set this attribute by code above  function addBuilder(...).
`bmb.setButtonEnum(ButtonEnum.Ham);
bmb.setPiecePlaceEnum(PiecePlaceEnum.HAM_6);
bmb.setButtonPlaceEnum(ButtonPlaceEnum.HAM_6);`

I don't know why? But if I put atrribute of BoomMenu to xml, I will get error:
`java.lang.IndexOutOfBoundsException: Index: 0, Size: 0 `

I try to dubug in BoomMenuButton class. I see function createPieces() run before function  addBuilder(...). So when it get item from arraylist boomButtonBuilders while  it is null.
if I add attribute by code before function addBuilder(...), it is not error.

I hope this can help you. :)

**Comment by 8bun** [comment]
Yes,it is a solution.
