### ISSUE TITLE
Crash issue after downloading large amount data

### ISSUE THREAD

**Issue by praveenb** [Nightonke/BoomMenu#142]
I've two screens, Home Screen and Settings screen. (This Settings screen used for downloading some large xml data.)

I've placed boom menu in Home screen as shown below. 

        bmbe.setButtonEnum(ButtonEnum.TextOutsideCircle);
        bmbe.setPiecePlaceEnum(PiecePlaceEnum.DOT_6_1);
        bmbe.setButtonPlaceEnum(ButtonPlaceEnum.SC_6_1);

And after downloading all data in Settings screen, if i come back to Home screen, boom menu doesn't show any pieces in it. and when i clicked on it get below crash

```
java.lang.RuntimeException: Unknown button-enum!
at com.nightonke.boommenu.ExceptionManager.judge(ExceptionManager.java:21)
at com.nightonke.boommenu.BoomMenuButton.innerBoom(BoomMenuButton.java:551)
at com.nightonke.boommenu.BoomMenuButton.boom(BoomMenuButton.java:540)
at com.nightonke.boommenu.BoomMenuButton$1.onClick(BoomMenuButton.java:312)
at android.view.View.performClick(View.java:5612)
at android.view.View$PerformClick.run(View.java:22285)
at android.os.Handler.handleCallback(Handler.java:751)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6123)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)

```
And No crash, If i've not downloaded, just goto Settings scren and come back to Home screen

Thank you.

**Comment by praveenb** [comment]
I solved this by re-initializing boommenu in MainActivity onResume method

   ```
@Override
    protected void onResume() {
           super.onResume();
		if(bmbe.getBuilders()!=null)
                bmbe.clearBuilders();

            initBmb();
            Log.d(TAG,"In MainActivity!--> visible, init bmb");
	}
```

Hope it may help somebody.
Thank you so much for wonderful control anyway.
