### ISSUE TITLE
Field crash

### ISSUE THREAD

**Issue by ankitbatra11** [Nightonke/BoomMenu#143]
```
Fatal Exception: java.lang.IllegalArgumentException: width and height must be > 0
       at android.graphics.Bitmap.createBitmap(Bitmap.java:922)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:901)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:868)
       at com.nightonke.boommenu.BMBShadow.b(Unknown Source)
       at com.nightonke.boommenu.BMBShadow.onLayout(Unknown Source)
       at android.view.View.layout(View.java:15551)
       at android.view.ViewGroup.layout(ViewGroup.java:4856)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
       at com.nightonke.boommenu.BoomMenuButton.onLayout(Unknown Source)
       at android.view.View.layout(View.java:15551)
       at android.view.ViewGroup.layout(ViewGroup.java:4856)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
       at android.view.View.layout(View.java:15551)
       at android.view.ViewGroup.layout(ViewGroup.java:4856)
       at android.support.design.widget.CoordinatorLayout.a(Unknown Source)
       at android.support.design.widget.CoordinatorLayout.onLayout(Unknown Source)
       at android.view.View.layout(View.java:15551)
       at android.view.ViewGroup.layout(ViewGroup.java:4856)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
       at android.view.View.layout(View.java:15551)
       at android.view.ViewGroup.layout(ViewGroup.java:4856)
       at android.support.v7.widget.ActionBarOverlayLayout.onLayout(Unknown Source)
       at android.view.View.layout(View.java:15551)
       at android.view.ViewGroup.layout(ViewGroup.java:4856)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
       at android.view.View.layout(View.java:15551)
       at android.view.ViewGroup.layout(ViewGroup.java:4856)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1677)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1531)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1440)
       at android.view.View.layout(View.java:15551)
       at android.view.ViewGroup.layout(ViewGroup.java:4856)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
       at android.view.View.layout(View.java:15551)
       at android.view.ViewGroup.layout(ViewGroup.java:4856)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2285)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2002)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1228)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6386)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:803)
       at android.view.Choreographer.doCallbacks(Choreographer.java:603)
       at android.view.Choreographer.doFrame(Choreographer.java:573)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:789)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:157)
       at android.app.ActivityThread.main(ActivityThread.java:5377)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by Nightonke** [comment]
The exception-protect is added since version 2.1.1. #134
