### ISSUE TITLE
Memory optimization needed

### ISSUE THREAD

**Issue by hisham2007** [Nightonke/BoomMenu#15]
Crashlytics reported that 13 crash happened because of out of memory issue.

**important stack trace part:**

at com.nightonke.boommenu.Util.setCircleButtonStateListDrawable(Util.java:69)
at com.nightonke.boommenu.BoomMenuButton.setBoomButtonBackgroundColor(BoomMenuButton.java:1368)
at com.nightonke.boommenu.BoomMenuButton.(BoomMenuButton.java)

**full stack trace:**

Fatal Exception: java.lang.RuntimeException
Unable to start activity ComponentInfo{com.tabe3.news/com.tabe3.news.ui.activity.FeedDetailsActivity}: android.view.InflateException: Binary XML file line #259: Error inflating class <unknown>
 raw

Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.tabe3.news/com.tabe3.news.ui.activity.FeedDetailsActivity}: android.view.InflateException: Binary XML file line #259: Error inflating class <unknown>
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2413)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2471)
       at android.app.ActivityThread.access$900(ActivityThread.java:175)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5602)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by android.view.InflateException: Binary XML file line #259: Error inflating class <unknown>
       at android.view.LayoutInflater.createView(LayoutInflater.java:626)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.createCustomViewInternal(CalligraphyLayoutInflater.java:211)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.access$000(CalligraphyLayoutInflater.java:20)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater$PrivateWrapperFactory2.onCreateView(CalligraphyLayoutInflater.java:302)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:695)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:769)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:769)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:498)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:354)
       at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:256)
       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109)
       at com.tabe3.news.ui.activity.FeedDetailsActivity.onCreate(FeedDetailsActivity.java:319)
       at android.app.Activity.performCreate(Activity.java:5451)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2377)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2471)
       at android.app.ActivityThread.access$900(ActivityThread.java:175)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5602)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by java.lang.reflect.InvocationTargetException
       at java.lang.reflect.Constructor.constructNative(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
       at android.view.LayoutInflater.createView(LayoutInflater.java:600)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.createCustomViewInternal(CalligraphyLayoutInflater.java:211)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.access$000(CalligraphyLayoutInflater.java:20)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater$PrivateWrapperFactory2.onCreateView(CalligraphyLayoutInflater.java:302)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:695)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:769)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:769)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:498)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:354)
       at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:256)
       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109)
       at com.tabe3.news.ui.activity.FeedDetailsActivity.onCreate(FeedDetailsActivity.java:319)
       at android.app.Activity.performCreate(Activity.java:5451)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2377)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2471)
       at android.app.ActivityThread.access$900(ActivityThread.java:175)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5602)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by java.lang.OutOfMemoryError
       at android.graphics.Bitmap.nativeCreate(Bitmap.java)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:928)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:901)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:868)
       at com.nightonke.boommenu.Util.setCircleButtonStateListDrawable(Util.java:69)
       at com.nightonke.boommenu.BoomMenuButton.setBoomButtonBackgroundColor(BoomMenuButton.java:1368)
       at com.nightonke.boommenu.BoomMenuButton.(BoomMenuButton.java)
       at java.lang.reflect.Constructor.constructNative(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
       at android.view.LayoutInflater.createView(LayoutInflater.java:600)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.createCustomViewInternal(CalligraphyLayoutInflater.java:211)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.access$000(CalligraphyLayoutInflater.java:20)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater$PrivateWrapperFactory2.onCreateView(CalligraphyLayoutInflater.java:302)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:695)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:769)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:769)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:498)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:354)
       at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:256)
       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109)
       at com.tabe3.news.ui.activity.FeedDetailsActivity.onCreate(FeedDetailsActivity.java:319)
       at android.app.Activity.performCreate(Activity.java:5451)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2377)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2471)
       at android.app.ActivityThread.access$900(ActivityThread.java:175)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5602)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by naveedahmad99** [comment]
Same issue with me

**Comment by Nightonke** [comment]
That's really strange... May I get the code where the bug happens?

**Comment by naveedahmad99** [comment]
Ok I will share my project zip with you soon

**Comment by hisham2007** [comment]
I included in bug description the lines that cause issue

**Comment by hisham2007** [comment]
I hope you can fix this issue as its impact is increased. crashlytics says that 33 crash happened to 19 user

**Comment by Nightonke** [comment]
@hisham2007 I'm sorry to hear that. I will fix this as soon as possible. Is it possible that the images of sub buttons are so large that the out-of-memory crash happens?
@naveedahmad99 I haven't got the zip. Could you send your code to me at your convenient?

**Comment by Nightonke** [comment]
Hey guys. I have used MAT to analyse the BMB sample project and I didn't find the reason why out-of-memory crash happen(This problem didn't happen on my mobile). But I have tried to do some memory optimization in the new version 1.0.8. I'm not sure whether it works. I will wait for the code-zip from @naveedahmad99 and your responses. Really sorry that BMB crashed your projects.

**Comment by naveedahmad99** [comment]
I will upload the zip tomorrow because I have the code in office computer.

**Comment by naveedahmad99** [comment]
Its ok @Nightonke Crashes are part of the successful stories. We will contribute to make it working, Thank you so much for your time.

**Comment by naveedahmad99** [comment]
@Nightonke [here ](https://www.dropbox.com/s/6z4cktbxmo33dld/boom.rar?dl=0)is the test project which were causing crash with BoomMenu

**Comment by hisham2007** [comment]
I don't use big images. I am not using images at all. I use font:
`private void initBoom() {
        int number = 7;

        Drawable facebookDrawable = new IconicsDrawable(this, FontAwesome.Icon.faw_facebook_official).color(Color.WHITE).paddingDp(24);
        Drawable mailDrawable = new IconicsDrawable(this, GoogleMaterial.Icon.gmd_email).paddingDp(24).color(Color.WHITE);
        Drawable twitterDrawable = new IconicsDrawable(this, FontAwesome.Icon.faw_twitter_square).paddingDp(24).color(Color.WHITE);
        Drawable googleplusDrawable = new IconicsDrawable(this, FontAwesome.Icon.faw_google_plus_square).paddingDp(24).color(Color.WHITE);
        Drawable copyDrawable = new IconicsDrawable(this, FontAwesome.Icon.faw_copy).paddingDp(24).color(Color.WHITE);
        Drawable smsDrawable = new IconicsDrawable(this, GoogleMaterial.Icon.gmd_sms).paddingDp(24).color(Color.WHITE);
        Drawable otherDrawable = new IconicsDrawable(this, GoogleMaterial.Icon.gmd_share).paddingDp(24).color(Color.WHITE);

        Drawable[] drawables = {otherDrawable, facebookDrawable, twitterDrawable, googleplusDrawable, mailDrawable, smsDrawable, copyDrawable};


        int[] facebookColor = {getResources().getColor(R.color.myPrimaryColor), getResources().getColor(R.color.myPrimaryColor)};
        int[] twitterColor = {getResources().getColor(R.color.myPrimaryColor), getResources().getColor(R.color.myPrimaryColor)};
        int[] googleColor = {getResources().getColor(R.color.myAccentColor2), getResources().getColor(R.color.myAccentColor2)};
        int[] mailColor = {getResources().getColor(R.color.window_background), getResources().getColor(R.color.window_background)};
        int[] smsColor = {getResources().getColor(R.color.window_background), getResources().getColor(R.color.window_background)};
        int[] copyColor = {getResources().getColor(R.color.window_background), getResources().getColor(R.color.window_background)};
        int[] otherColor = {getResources().getColor(R.color.window_background), getResources().getColor(R.color.window_background)};



        String[] strings = new String[number];
        for (int i = 0; i < number; i++)
            strings[i] = STRINGS[i];

        ///int[][] colors = {facebookColor,twitterColor,googleColor,mailColor,smsColor,copyColor,otherColor};
        int[][] colors = {googleColor, googleColor, googleColor, googleColor, googleColor, googleColor, googleColor};


        btnMainAction.init(
                drawables,                  // The drawables of images of sub buttons. Can not be null.
                strings,                    // The texts of sub buttons, ok to be null.
                colors,                     // The colors of sub buttons, including pressed-state and normal-state.
                ButtonType.CIRCLE,          // The button type.
                BoomType.HORIZONTAL_THROW_2,// The boom type.
                PlaceType.SHARE_7_3,             // The place type.
                null,                       // Ease type to move the sub buttons when showing.
                null,                       // Ease type to scale the sub buttons when showing.
                null,                       // Ease type to rotate the sub buttons when showing.
                null,                       // Ease type to move the sub buttons when dismissing.
                null,                       // Ease type to scale the sub buttons when dismissing.
                null,                       // Ease type to rotate the sub buttons when dismissing.
                null                        // Rotation degree.
        );
        btnMainAction.setShareLineWidth(6);
        btnMainAction.setSubButtonShadowOffset(Util.getInstance().dp2px(2), Util.getInstance().dp2px(2));
        btnMainAction.setShareLine1Color(Color.WHITE);
        btnMainAction.setShareLine2Color(Color.WHITE);
        btnMainAction.setDuration(500);
        btnMainAction.setRotateDegree(360);
        btnMainAction.setHideOrderType(OrderType.REVERSE);
        btnMainAction.setOnSubButtonClickListener(this);

        btnMainAction.setAnimatorListener(new BoomMenuButton.AnimatorListener() {
            @Override
            public void toShow() {

            }

            @Override
            public void showing(float fraction) {

            }

            @Override
            public void showed() {

            }

            @Override
            public void toHide() {

            }

            @Override
            public void hiding(float fraction) {

            }

            @Override
            public void hided() {
                if(buttonIndex!=-1){
                    AnalyticsUtil.trackEvent("showFab_detailsScreen_" + STRINGS[buttonIndex], "feedTitle", feed.getTitle());
                    presenter.feedShared(feed.getId());
                    UiUtil.showShareDialog(FeedDetailsActivity.this, bottomsheet, feed.getChannelName() + " - " + feed.getTitle(), "www.tabe3news.com/feeds/" + feed.getId(), feed.getMediaUrl(), feed.getTitle(), feed.getId(), branchUniversalObject,buttonIndex);

                }
             buttonIndex=-1;
            }
        });
    }`

**Comment by Nightonke** [comment]
@naveedahmad99 I have tested your project and I didn't get any crash...
I have checked the monitor for memory used and everything goes well.

**Comment by Nightonke** [comment]
@hisham2007 @naveedahmad99 Please try the newest version and tell me whether the bug still exists. Thank you.

**Comment by Nightonke** [comment]
No reply for this bug. Now I close it and if someone find this bug still exists, just open it.

**Comment by hisham2007** [comment]
Ok thanks. I will try latest update and let you know
