### ISSUE TITLE
getActionBar returns null

### ISSUE THREAD

**Issue by AmirF194** [Nightonke/BoomMenu#158]
Hi,
Please help me !
I run this code in other app it work fine
but i add some library in my project i get this 
"Unfortunately,app has stopped"

final ActionBar mActionBar =getSupportActionBar();
        assert mActionBar != null;
// it crash here 
        mActionBar.setDisplayShowHomeEnabled(false);
        mActionBar.setDisplayShowTitleEnabled(false);
        LayoutInflater mInflater = LayoutInflater.from(this);
        final View actionBar = mInflater.inflate(R.layout.main, null);
        mActionBar.setCustomView(actionBar);
        mActionBar.setDisplayShowCustomEnabled(true);
        ((Toolbar) actionBar.getParent()).setContentInsetsAbsolute(0, 0);
        final BoomMenuButton leftBmb = (BoomMenuButton) actionBar.findViewById(R.id.action_bar_left_bmb);
        leftBmb.setButtonEnum(ButtonEnum.Ham);
        leftBmb.setAutoBoom(true);
        leftBmb.setAutoHide(true);
        leftBmb.setDelay(100);
        leftBmb.setHideDelay(200);
        leftBmb.setPiecePlaceEnum(PiecePlaceEnum.HAM_6);
        leftBmb.setButtonPlaceEnum(ButtonPlaceEnum.HAM_6);

10-11 13:58:25.971 16433-16433/com.example.sharif.boomtest E/AndroidRuntime: FATAL EXCEPTION: main
                                                                             Process: com.example.sharif.boomtest, PID: 16433
                                                                             java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.sharif.boomtest/com.example.sharif.boomtest.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.app.ActionBar.setDisplayShowHomeEnabled(boolean)' on a null object reference
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3320)
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3416)
                                                                                 at android.app.ActivityThread.access$1100(ActivityThread.java:230)
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1822)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                 at android.os.Looper.loop(Looper.java:148)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:7409)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                                              Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.app.ActionBar.setDisplayShowHomeEnabled(boolean)' on a null object reference
                                                                                 at com.example.sharif.boomtest.MainActivity.StartingMenu(MainActivity.java:82)
                                                                                 at com.example.sharif.boomtest.MainActivity.onCreate(MainActivity.java:77)
                                                                                 at android.app.Activity.performCreate(Activity.java:6904)
                                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1136)
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3267)
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3416) 
                                                                                 at android.app.ActivityThread.access$1100(ActivityThread.java:230) 
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1822) 
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                 at android.os.Looper.loop(Looper.java:148) 
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:7409) 
                                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by gcantoni** [comment]
up
