### ISSUE TITLE
NullPointerException occurred when I click the circleBoomMenuButton sometimes

### ISSUE THREAD

**Issue by qs73** [Nightonke/BoomMenu#17]
Whether through the two-dimensional code that the zip contains  to download the APK, or by my own sample that uses " compile 'com.nightonke:boommenu:1.0.8'"  , the emergence of this issue.
(无论是通过下载您的zip文档里的二维码安装的apk，还是我自己摘出的部分代码，使用了compile 'com.nightonke:boommenu:1.0.8'的方式，在多次点击circleBoomMenuButton时都出现了NullPointerException)，错误信息如下
java.lang.NullPointerException
            at android.animation.PropertyValuesHolder.setupSetterAndGetter(PropertyValuesHolder.java:505)
            at android.animation.ObjectAnimator.initAnimation(ObjectAnimator.java:487)
            at android.animation.ValueAnimator.setCurrentPlayTime(ValueAnimator.java:517)
            at android.animation.ValueAnimator.start(ValueAnimator.java:936)
            at android.animation.ValueAnimator.start(ValueAnimator.java:946)
            at android.animation.ObjectAnimator.start(ObjectAnimator.java:465)
            at com.nightonke.boommenu.BoomMenuButton.setHideAnimation(BoomMenuButton.java:1115)
            at com.nightonke.boommenu.BoomMenuButton.startHideAnimations(BoomMenuButton.java:1022)
            at com.nightonke.boommenu.BoomMenuButton.access$300(BoomMenuButton.java:47)
            at com.nightonke.boommenu.BoomMenuButton$2.onClick(BoomMenuButton.java:482)
            at android.view.View.performClick(View.java:4632)
            at android.view.View$PerformClick.run(View.java:19385)
            at android.os.Handler.handleCallback(Handler.java:808)
            at android.os.Handler.dispatchMessage(Handler.java:103)
            at android.os.Looper.loop(Looper.java:193)
            at android.app.ActivityThread.main(ActivityThread.java:5348)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by Nightonke** [comment]
I will check this. If you can tell me the situation when this bug happened, that would be helpful for solving this bug. Thanks for reporting.

**Comment by Aminuzp** [comment]
Hi,I have a similar problem.Please fix this problem.Thanks

**Comment by Nightonke** [comment]
@Aminuzp Can I get the code and the crash log? Thanks for reporting.

**Comment by Nightonke** [comment]
@qs73 The "circleBoomMenuButton", you mean, is the BMB or the sub buttons?

**Comment by Aminuzp** [comment]
@Nightonke Hi,My crash log and problem is the same @qs73 .And i implement your code Exactly.

**Comment by emadph** [comment]
@Nightonke same erorr ! 
i think that's happened when u clicked boom menu too fast.
now what ?!

**Comment by qs73** [comment]
@Nightonke the crash happened in "LISTVIEW EXAMPLE" ,even if I clicked  the boomMenu not so fast，it crashed. Could you help me solve the problem ?thanks !

**Comment by qs73** [comment]
@Nightonke there is the whole log information
Process: com.nightonke.boommenusample, PID: 22836
    java.lang.NullPointerException
            at android.animation.PropertyValuesHolder.setupSetterAndGetter(PropertyValuesHolder.java:792)
            at android.animation.ObjectAnimator.initAnimation(ObjectAnimator.java:784)
            at android.animation.ValueAnimator.setCurrentPlayTime(ValueAnimator.java:517)
            at android.animation.ValueAnimator.start(ValueAnimator.java:936)
            at android.animation.ValueAnimator.start(ValueAnimator.java:946)
            at android.animation.ObjectAnimator.start(ObjectAnimator.java:762)
            at com.nightonke.boommenu.BoomMenuButton.setHideAnimation(BoomMenuButton.java:1105)
            at com.nightonke.boommenu.BoomMenuButton.startHideAnimations(BoomMenuButton.java:1012)
            at com.nightonke.boommenu.BoomMenuButton.access$300(BoomMenuButton.java:44)
            at com.nightonke.boommenu.BoomMenuButton$2.onClick(BoomMenuButton.java:472)
            at android.view.View.performClick(View.java:4444)
            at android.view.View$PerformClick.run(View.java:18440)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5052)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by Nightonke** [comment]
I have updated a new version 1.0.9 to add codes to prevent this exception happening. Please check whether this issue was solved.

**Comment by Aminuzp** [comment]
Very thanks @Nightonke.

**Comment by Nightonke** [comment]
@Aminuzp I would like to help you to fix bugs. So... Was the bug fixed?

**Comment by PGMacDesign** [comment]
Note, this can also happen when you have the view set as `GONE`, set it to `VISIBLE` and then immediately hit the boom action. Simplest fix is just to add a `post` call to the view itself and nest your call under there. IE:

`


		this.boomMenu.post(() -> {

			this.boomMenu.boom();

		});



`
