### ISSUE TITLE
java.lang.ClassCastException:  

### ISSUE THREAD

**Issue by SQuizL** [Nightonke/BoomMenu#194]
Hello,

I'm using _boommenu:2.1.1_ and I'm having an infrequent problem with when I click to boom. Can anyone see if I'm doing anything wrong?

Thanks!

> java.lang.ClassCastException: 
>   at com.nightonke.boommenu.BackgroundView.reLayout (BackgroundView.java:50)
>   at com.nightonke.boommenu.BoomMenuButton$9.run (BoomMenuButton.java:1106)
>   at android.os.Handler.handleCallback (Handler.java:789)
>   at android.os.Handler.dispatchMessage (Handler.java:98)
>   at android.os.Looper.loop (Looper.java:164)
>   at android.app.ActivityThread.main (ActivityThread.java:6798)
>   at java.lang.reflect.Method.invoke (Native Method)
>   at com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:240)
>   at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:767)

  ```
 <GridLayout
                    android:id="@+id/layoutPalette"
                    android:layout_width="fill_parent"
                    android:layout_height="wrap_content"
                    android:layout_marginBottom="5dp"
                    android:layout_marginTop="5dp"
                    android:orientation="horizontal"
                    android:tag="Palette">


                    <com.nightonke.boommenu.BoomMenuButton
                        android:id="@+id/bmb"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:layout_marginBottom="-10dp"
                        >

                        <LinearLayout
                            android:layout_width="wrap_content"
                            android:layout_height="wrap_content"
                            android:layout_marginLeft="2dp"
                            android:layout_weight="1.2"
                            android:background="@drawable/filter"
                            android:orientation="horizontal" />


                    </com.nightonke.boommenu.BoomMenuButton>

```

```
private BoomMenuButton bmb;

bmb = (BoomMenuButton) findViewById(R.id.bmb);

        bmb.setButtonEnum(ButtonEnum.TextInsideCircle);
        bmb.setPiecePlaceEnum(PiecePlaceEnum.DOT_6_1);
        bmb.setButtonPlaceEnum(ButtonPlaceEnum.SC_6_1);

        bmb.setOnBoomListener(
                new OnBoomListenerAdapter() {
                    @Override
                    public void onBoomWillShow() {
                        super.onBoomWillShow();
                        bmb.setOrientationAdaptable(true);
                    }
                    @Override
                    public void onBoomDidHide() {
                        super.onBoomDidHide();
                        bmb.setOrientationAdaptable(false);
                    }
                });

        for (int i = 0; i < bmb.getPiecePlaceEnum().pieceNumber(); i++) {
            //Log.d("img",Integer.toString(fImg.getIndex(i)));
            TextInsideCircleButton.Builder builder = new TextInsideCircleButton.Builder()
                    .isRound(false)
                    .shadowCornerRadius(Util.dp2px(10))
                    .buttonCornerRadius(Util.dp2px(10))
                    .imagePadding(new Rect(0, 0, 0, 12))
                    .normalImageRes(fImg.getResourceId(i, -1))
                    .normalText(Fnme[i])
                    .textPadding(new Rect(0, 22, 0, 0))
                    .normalColorRes(fCol.getResourceId(i, -1))
                    .listener(new OnBMClickListener() {
                        @Override
                        public void onBoomButtonClick(int index) {
               
                           //my stuff
                        }
                    });
            bmb.addBuilder(builder);
        }

```

**Comment by SQuizL** [comment]
> 06-12 11:15:48.729 11494-11494/draganddrop.android.project E/AndroidRuntime: FATAL EXCEPTION: main
>     Process: draganddrop.android.project, PID: 11494
>     java.lang.ClassCastException: android.widget.GridLayout$LayoutParams cannot be cast to android.widget.FrameLayout$LayoutParams
>         at com.nightonke.boommenu.BackgroundView.reLayout(BackgroundView.java:50)
>         at com.nightonke.boommenu.BoomMenuButton$9.run(BoomMenuButton.java:1106)
>         at android.os.Handler.handleCallback(Handler.java:789)
>         at android.os.Handler.dispatchMessage(Handler.java:98)
>         at android.os.Looper.loop(Looper.java:164)
>         at android.app.ActivityThread.main(ActivityThread.java:6798)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by SQuizL** [comment]
It seems that the code: 
 ```
   protected void reLayout(final BoomMenuButton bmb) {
        ViewGroup rootView = bmb.getParentView();
        FrameLayout.LayoutParams params = (LayoutParams) getLayoutParams();
        params.width = rootView.getWidth();
        params.height = rootView.getHeight();
        setLayoutParams(params);
    }

```
assumes that the parent view is the highest level and is where the boom is drawn.

**Comment by SQuizL** [comment]
Fixed it!

```
 protected void reLayout(final BoomMenuButton bmb) {

        **ViewGroup vw = bmb.getParentView();
        ViewGroup rootView  = (ViewGroup) vw.getRootView();**

        Log.d("trigger", "reLayout: fixes");

        FrameLayout.LayoutParams params = (LayoutParams) getLayoutParams();

        params.width = rootView.getWidth();
        params.height = rootView.getHeight();
        setLayoutParams(params);
    }
```
