### ISSUE TITLE
   My app crashes whenever the boom menu bottom is clicked

### ISSUE THREAD

**Issue by acj9189** [Nightonke/BoomMenu#217]
Hi....

    i have the same error.....

    can you help me with that...

    My app crashes whenever the boom menu bottom is clicked

    java.lang.RuntimeException: Unknown button-enum!
    at com.nightonke.boommenu.ExceptionManager.judge(ExceptionManager.java:21)
    at com.nightonke.boommenu.BoomMenuButton.innerBoom(BoomMenuButton.java:562)
    at com.nightonke.boommenu.BoomMenuButton.boom(BoomMenuButton.java:551)
    at com.nightonke.boommenu.BoomMenuButton$1.onClick(BoomMenuButton.java:320)
    at android.view.View.performClick(View.java:6256)
    at android.view.View$PerformClick.run(View.java:24701)
    at android.os.Handler.handleCallback(Handler.java:789)
    at android.os.Handler.dispatchMessage(Handler.java:98)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6541)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

    That's really weird. The code about the crash is here, which I believe there wouldn't be any bugs. I test sample apks on other devices and there're no crashes. I'm considering use ArrayList to protect the "ArrayIndexOutOfBoundsException"(But why the exception happens?)

Hi....

i have the same error.....

can you help me with that...

My app crashes whenever the boom menu bottom is clicked

java.lang.RuntimeException: Unknown button-enum!
at com.nightonke.boommenu.ExceptionManager.judge(ExceptionManager.java:21)
at com.nightonke.boommenu.BoomMenuButton.innerBoom(BoomMenuButton.java:562)
at com.nightonke.boommenu.BoomMenuButton.boom(BoomMenuButton.java:551)
at com.nightonke.boommenu.BoomMenuButton$1.onClick(BoomMenuButton.java:320)
at android.view.View.performClick(View.java:6256)
at android.view.View$PerformClick.run(View.java:24701)
at android.os.Handler.handleCallback(Handler.java:789)
at android.os.Handler.dispatchMessage(Handler.java:98)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6541)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by majid1605** [comment]
Hi
this is my code 

<com.nightonke.boommenu.BoomMenuButton
            android:id="@+id/bmb"
            android:layout_width="60dp"
            android:layout_height="match_parent"
            android:layout_alignParentStart="true"
            android:layout_centerVertical="true"
            app:bmb_backgroundEffect="false"
            app:bmb_boomEnum="boomParabola_3"
            app:bmb_buttonEnum="ham"
            app:bmb_piecePlaceEnum="piecePlace_dot_3_1"
            app:bmb_buttonPlaceEnum="buttonPlace_sc_3_3"/>

kotlin code:
for (i in 0 until bmb.piecePlaceEnum.pieceNumber())
        {
            val builder = SimpleCircleButton.Builder().normalImageRes(R.drawable.ic_define_cost)
            bmb.addBuilder(builder)
        }


and i have the same error.

**Comment by colorgold** [comment]
This is a bit late, but here is how I handled the click events:
`bmb.setOnBoomListener(new OnBoomListener() {
            @Override
            public void onClicked(int index, BoomButton boomButton) {
                // If you have implement listeners for boom-buttons in builders,
                // then you shouldn't add any listener here for duplicate callbacks.
            }`


Or, check out this link to see their demo:
*edit: forgot to include link*
[https://github.com/Nightonke/BoomMenu/blob/master/app/src/main/java/com/nightonke/boommenusample/ListenerActivity.java](url)
