### ISSUE TITLE
Fatal Exception: java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by georgi58** [Nightonke/BoomMenu#219]
The implementation of BoomMenuButton is written entirely in a try-catch block. Why it happens?

Fatal Exception: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
       at java.util.ArrayList.get(ArrayList.java:411)
       at com.nightonke.boommenu.BoomMenuButton.startReboomAnimations(BoomMenuButton.java:674)
       at com.nightonke.boommenu.BoomMenuButton.innerReboom(BoomMenuButton.java:594)
       at com.nightonke.boommenu.BoomMenuButton.reboom(BoomMenuButton.java:580)
       at com.nightonke.boommenu.BoomMenuButton.onBackgroundClicked(BoomMenuButton.java:884)
       at com.nightonke.boommenu.BackgroundView$1.onClick(BackgroundView.java:41)
       at android.view.View.performClick(View.java:5646)
       at android.view.View$PerformClick.run(View.java:22473)
       at android.os.Handler.handleCallback(Handler.java:761)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:156)
       at android.app.ActivityThread.main(ActivityThread.java:6523)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

**Comment by OmarSakr** [comment]
did anyone find the solution

**Comment by lucazin** [comment]
omg ..im stuck in this problem.
