### ISSUE TITLE
Null Pointer exception onClick subMenuItem in Actiobar BoomMenu

### ISSUE THREAD

**Issue by burhanrashid52** [Nightonke/BoomMenu#32]
```
 E/AndroidRuntime: FATAL EXCEPTION: main
                                                                              Process: com.nightonke.boommenusample, PID: 32358
                                                                              java.lang.NullPointerException: Attempt to invoke virtual method 'android.widget.TextView com.nightonke.boommenu.CircleButton.getTextView()' on a null object reference
                                                                                  at com.nightonke.boommenu.BoomMenuButton.getTextViews(BoomMenuButton.java:1382)
                                                                                  at com.nightonke.boommenusample.MainActivity.onClick(MainActivity.java:641)
                                                                                  at com.nightonke.boommenu.BoomMenuButton.onClick(BoomMenuButton.java:1630)
                                                                                  at com.nightonke.boommenu.CircleButton$1.onClick(CircleButton.java:108)
                                                                                  at android.view.View.performClick(View.java:5269)
                                                                                  at android.view.View$PerformClick.run(View.java:21556)
                                                                                  at android.os.Handler.handleCallback(Handler.java:815)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                                  at android.os.Looper.loop(Looper.java:207)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5776)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
```

**Comment by Nightonke** [comment]
Hey, please check the newest version and tell my whether this bug still exists.

**Comment by burhanrashid52** [comment]
Hello
I have checked that issue and now it's working perfectly....nice job
man...your contributions is going to be huge for developer's community

**Comment by Nightonke** [comment]
Thanks, just a little job.
