### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by joshuaavalon** [Nightonke/BoomMenu#48]
I am trying to use `BoomMenuButton` in a fragment.

My XML,

```
 <com.nightonke.boommenu.BoomMenuButton
    android:id="@+id/boom"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:layout_gravity="bottom|end"
    android:layout_alignParentBottom="true"
    android:layout_alignParentEnd="true"
    android:layout_margin="@dimen/fab_margin"
    app:boom_button_color="@color/colorPrimary"
    app:boom_button_pressed_color="@color/colorPrimary"
    app:boom_inActionBar="false" />
```

In `onCreateView`,

```
boomMenuButton = (BoomMenuButton) view.findViewById(R.id.boom);
```

In `onWindowFocusChanged`,

```
new BoomMenuButton.Builder()
        .addSubButton(ContextCompat.getDrawable(getContext(), R.drawable.ic_info_outline_white_24dp),
                new int[]{ContextCompat.getColor(getContext(), R.color.white)},
                "BoomMenuButton")
        .addSubButton(ContextCompat.getDrawable(getContext(), R.drawable.ic_info_outline_white_24dp),
                new int[]{ContextCompat.getColor(getContext(), R.color.white)},
                "BoomMenuButton")
        .addSubButton(ContextCompat.getDrawable(getContext(), R.drawable.ic_info_outline_white_24dp),
                new int[]{ContextCompat.getColor(getContext(), R.color.white)},
                "BoomMenuButton")
        .button(ButtonType.HAM)
        .boom(BoomType.PARABOLA)
        .place(PlaceType.HAM_3_1)
        .subButtonTextColor(ContextCompat.getColor(getContext(), R.color.white))
        .init(boomMenuButton);
```

When I clicked the button, the app crash

```
java.lang.NullPointerException: Attempt to read from field 'int com.nightonke.boommenu.Types.PlaceType.v' on a null object reference
     at com.nightonke.boommenu.BoomMenuButton.dimAnimationLayout(BoomMenuButton.java:516)
     at com.nightonke.boommenu.BoomMenuButton.shoot(BoomMenuButton.java:467)
     at com.nightonke.boommenu.BoomMenuButton.access$000(BoomMenuButton.java:47)
     at com.nightonke.boommenu.BoomMenuButton$9.onClick(BoomMenuButton.java:1500)
     at android.view.View.performClick(View.java:5197)
     at android.view.View$PerformClick.run(View.java:20926)
     at android.os.Handler.handleCallback(Handler.java:739)
     at android.os.Handler.dispatchMessage(Handler.java:95)
     at android.os.Looper.loop(Looper.java:145)
     at android.app.ActivityThread.main(ActivityThread.java:5951)
     at java.lang.reflect.Method.invoke(Native Method)
     at java.lang.reflect.Method.invoke(Method.java:372)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
```

**Comment by soad130** [comment]
same issue :((

**Comment by zahansafallwa** [comment]
can you specify the line where the error the occur in your code

**Comment by joshuaavalon** [comment]
@zahansafallwa As you see in the exception, the `NullPointerException` is thrown in the library.

**Comment by Nightonke** [comment]
Hey! Now the newest version of BMB was updated. Please use the newest version and let me know whether the bug is fixed.

**Comment by gcantoni** [comment]
I'm getting `NullPointerException ` too. How did you solve?
