### ISSUE TITLE
HamButton.Builder 设置 containsSubText(false) 抛异常

### ISSUE THREAD

**Issue by qq2653203** [Nightonke/BoomMenu#62]
错误如下：
 java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setTextColor(int)' on a null object reference
                                                                         at com.nightonke.boommenu.BoomButtons.BoomButton.toNormalSubText(BoomButton.java:533)
                                                                         at com.nightonke.boommenu.BoomButtons.HamButton.toNormal(HamButton.java:101)
                                                                         at com.nightonke.boommenu.BoomButtons.BoomButton.initImage(BoomButton.java:274)
                                                                         at com.nightonke.boommenu.BoomButtons.HamButton.init(HamButton.java:40)
.......

**Comment by qq2653203** [comment]
代码如下：
![image](https://cloud.githubusercontent.com/assets/8454148/21173084/ed4ce7c8-c210-11e6-82ca-735ba5cd91fd.png)

**Comment by Nightonke** [comment]
I will check this tonight.

**Comment by Nightonke** [comment]
This is a bug in BMB which will be fixed in version 2.0.2. Thanks for feedback.

**Comment by qq2653203** [comment]
good job
