### ISSUE TITLE
App Crashes on click

### ISSUE THREAD

**Issue by faladinojames** [Nightonke/BoomMenu#64]
My app crashes whenever the boom menu bottom is clicked with ArrayIndexOutOfBoundsException. 
This only happens in the release version. The debug version works fine.

Android Device version: 6.0

The sample apks also crash on this device.

**Comment by Nightonke** [comment]
Would you please show me your code?

**Comment by faladinojames** [comment]
I have upgraded to version 2 to see if the problem will be fixed. But I am getting unknown button enum after following the steps in the wiki page.

**Comment by Nightonke** [comment]
Hey, bro. Just show me your code and let's check the problem.

**Comment by faladinojames** [comment]
XML

`<com.nightonke.boommenu.BoomMenuButton
                        android:id="@+id/boomDomicileMenu"
                        android:layout_width="60dp"
                        android:layout_height="match_parent"
                        android:layout_alignParentStart="true"
                        android:layout_alignParentLeft="true"
                        android:layout_centerVertical="true"
                        app:bmb_backgroundEffect="false"
                        app:bmb_boomEnum="boomParabola_2"
                        android:layout_gravity="left|center_vertical"/>`
.java


        BoomMenuButton boom2=(BoomMenuButton)findViewById(R.id.boomDomicileMenu);`

`      boom2.setButtonEnum(ButtonEnum.Ham);
        boom2.setPiecePlaceEnum(PiecePlaceEnum.HAM_4);
        boom2.setButtonPlaceEnum(ButtonPlaceEnum.HAM_4);
        for (int i = 0; i < boom2.getPiecePlaceEnum().pieceNumber(); i++)
            boom2.addBuilder( new HamButton.Builder()
                    .normalImageRes(R.drawable.photo)
                    .normalText("Butter Doesn't fly!")
                    .subNormalText("Little butter Doesn't fly, either!"));`

Crash:
java.RuntimeException. Unknown button-enum!
at com.nightonke.boommenu.ExceptionManager.judge(ExceptionManager.java:76)

**Comment by Nightonke** [comment]
Hey, you forget the code app:bmb_buttonEnum="ham".

**Comment by faladinojames** [comment]
I did that in the .Java file

**Comment by faladinojames** [comment]
It seems it's the app that has a problem.
But I think I have fixed it.
Thanks Anyways

**Comment by Nightonke** [comment]
Nice!

**Comment by faladinojames** [comment]
The initial problem still exists.
In the debug build, the app works just fine.
But after compiling in release mode with proguard. I get this error anytime the BoomMenuButton is clicked.

java.lang.ArrayIndexOutOfBoundsException: length=61;index=61
at com.nightonke.boommenu.Animation.AnimationManager.calculateShowXY(Unknown Source)
at com.nightonke.boomenu.BoomMenuButton.startEachShowAnimation(Unknown Source)
.........

Note that the sample apks also crash on the device. So, I guess its a general problem.
Device details:
Brand: Infinix
Device: Infinix_X510_sprout
Model: Infinix X510
SDK: 23
Release: 6.0
Incremental: 1476672601

**Comment by Nightonke** [comment]
That's really weird. The code about the crash is [here](https://github.com/Nightonke/BoomMenu/blob/master/boommenu/src/main/java/com/nightonke/boommenu/Animation/AnimationManager.java#L168), which I believe there wouldn't be any bugs. I test sample apks on other devices and there're no crashes. I'm considering use ArrayList to protect the "ArrayIndexOutOfBoundsException"(But why the exception happens?)

**Comment by faladinojames** [comment]
Searched online. Found a similar bug
https://github.com/google/ExoPlayer/issues/748

**Comment by Nightonke** [comment]
Thanks for your search. I will add a protect-logic tonight(Beijing Time).

**Comment by faladinojames** [comment]
Alright. Thanks in advance

**Comment by Nightonke** [comment]
@faladinojames Try version 2.0.5~

**Comment by faladinojames** [comment]
Waoh. Thanks. It now works

**Comment by Nightonke** [comment]
Nice!

**Comment by Maddumage** [comment]
Error:(21, 34) String types not allowed (at 'bmb_buttonPlaceEnum' with value 'buttonPlace_ham_4').

**Comment by acj9189** [comment]
Hi....

i have the same error..... 

can you help me with that...

My app crashes whenever the boom menu bottom is clicked

java.lang.RuntimeException: Unknown button-enum!
        at com.nightonke.boommenu.ExceptionManager.judge(ExceptionManager.java:21)
        at com.nightonke.boommenu.BoomMenuButton.innerBoom(BoomMenuButton.java:562)
        at com.nightonke.boommenu.BoomMenuButton.boom(BoomMenuButton.java:551)
        at com.nightonke.boommenu.BoomMenuButton$1.onClick(BoomMenuButton.java:320)
        at android.view.View.performClick(View.java:6256)
        at android.view.View$PerformClick.run(View.java:24701)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by acj9189** [comment]
> 
> 
> Hi....
> 
> i have the same error.....
> 
> can you help me with that...
> 
> My app crashes whenever the boom menu bottom is clicked
> 
> java.lang.RuntimeException: Unknown button-enum!
> at com.nightonke.boommenu.ExceptionManager.judge(ExceptionManager.java:21)
> at com.nightonke.boommenu.BoomMenuButton.innerBoom(BoomMenuButton.java:562)
> at com.nightonke.boommenu.BoomMenuButton.boom(BoomMenuButton.java:551)
> at com.nightonke.boommenu.BoomMenuButton$1.onClick(BoomMenuButton.java:320)
> at android.view.View.performClick(View.java:6256)
> at android.view.View$PerformClick.run(View.java:24701)
> at android.os.Handler.handleCallback(Handler.java:789)
> at android.os.Handler.dispatchMessage(Handler.java:98)
> at android.os.Looper.loop(Looper.java:164)
> at android.app.ActivityThread.main(ActivityThread.java:6541)
> at java.lang.reflect.Method.invoke(Native Method)
> at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)



> 
> 
> That's really weird. The code about the crash is [here](https://github.com/Nightonke/BoomMenu/blob/master/boommenu/src/main/java/com/nightonke/boommenu/Animation/AnimationManager.java#L168), which I believe there wouldn't be any bugs. I test sample apks on other devices and there're no crashes. I'm considering use ArrayList to protect the "ArrayIndexOutOfBoundsException"(But why the exception happens?)

Hi....

i have the same error.....

can you help me with that...

My app crashes whenever the boom menu bottom is clicked

java.lang.RuntimeException: Unknown button-enum!
at com.nightonke.boommenu.ExceptionManager.judge(ExceptionManager.java:21)
at com.nightonke.boommenu.BoomMenuButton.innerBoom(BoomMenuButton.java:562)
at com.nightonke.boommenu.BoomMenuButton.boom(BoomMenuButton.java:551)
at com.nightonke.boommenu.BoomMenuButton$1.onClick(BoomMenuButton.java:320)
at android.view.View.performClick(View.java:6256)
at android.view.View$PerformClick.run(View.java:24701)
at android.os.Handler.handleCallback(Handler.java:789)
at android.os.Handler.dispatchMessage(Handler.java:98)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6541)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
